/// Flutter icons MyIconsitos
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIconsitos
///      fonts:
///       - asset: fonts/MyIconsitos.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyIconsitos {
  MyIconsitos._();

  static const _kFontFam = 'MyIconsitos';
  static const String _kFontPkg = null;

  static const IconData pasta = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData food_dish = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soda_with_straw = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
